### ISSUE TITLE
feat : 웹 알림에 대한 연구

### ISSUE THREAD

**Issue by WinterHana** [kuberMAPtes/practice-space#1]
## 웹 알림에 대한 연구 주제
- [x] 구현 방식에 대한 정보 수집
- [ ] 임시로 구현하기

## 문자 보내기에 대한 연구 주제
- [x] API를 이용해서 문자 보내기

자세한 내용은 [Github Wiki](https://github.com/kuberMAPtes/practice-space/wiki/%5BWinterhana%5D-%EC%9B%B9-%EC%95%8C%EB%A6%BC,-%EC%9C%84%ED%82%A4-%EA%B5%AC%ED%98%84,-%EC%B6%94%EC%B2%9C-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EC%97%B0%EA%B5%AC)를 참고해주세요.

## 기타 이슈
- [x] 뭐야 왜 푸시가 안되냐 이거

**Comment by seong-jin-jo** [comment]
너무 멋진 이슈에요.
